server:
  port: 8081

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true
      routes:
      - id: USER-FEIGN-SERVICE
        uri: lb://USER-FEIGN-SERVICE
        predicates:
          - Path=/user/**
        filters:
          - StripPrefix=1
          - RequestTime=true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org.springframework.cloud.gateway: debug